# Generated by Django 5.1 on 2025-10-19 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofessor',
            name='turma_padrao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Turma Padrão'),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='turno_padrao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno Padrão'),
        ),
        migrations.AddField(
            model_name='planodeaula',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilprofessor',
            name='escola',
            field=models.CharField(blank=True, default='SAUL BENNESBY', max_length=200, null=True, verbose_name='Escola Padrão'),
        ),
        migrations.AlterField(
            model_name='perfilprofessor',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Completo'),
        ),
    ]
