# Generated by Django 5.1 on 2025-10-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_perfilprofessor_turma_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprofessor',
            name='duracao_padrao',
            field=models.CharField(blank=True, default='4 horas', max_length=50, null=True, verbose_name='Duração Padrão da Aula'),
        ),
        migrations.AddField(
            model_name='perfilprofessor',
            name='espaco_padrao',
            field=models.CharField(blank=True, default='Sala e pátio escolar', max_length=100, null=True, verbose_name='Espaço Padrão'),
        ),
    ]
